<a href="https://colab.research.google.com/github/pmilks/cap-comp215/blob/main/Project%203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import animation
from scipy.signal import correlate2d

In [5]:
class Langton2D:
  def __init__(self, ant, n_rows, n_cols=None):
    n_cols = n_cols or n_rows
    self.state = np.ones((n_rows, n_cols), dtype=np.uint8)
    self.ant = (n_rows//2, n_cols//2)


In [23]:
"""
Ant Board & Color Board
Iterate through directions, changing order depending on color
Directions:
"""
down = np.array([[0, 1, 0],
    [0, 0, 0],
    [0, 0, 0]])
left = np.array([[0, 0, 0],
        [0, 0, 1],
        [0, 0, 0]])
up = np.array([[0, 0, 0],
      [0, 0, 0],
      [0, 1, 0]])
right = np.array([[0, 0, 0],
      [1, 0, 0],
      [0, 0, 0]])
directions = [left, up, right, down]


a = np.zeros((5,5))
a[2,2] = 1
kernel = np.array([[0,0,0],
                   [0,0,1],
                   [0,0,0],]) #left move


print(correlate2d(a,kernel,boundary='wrap',mode='same'))


class Langton2D:
  def __init__(self, ant, n_rows, n_cols):
    n_cols = n_cols or n_rows
    self.ant = Ant(dir=1,clr=True)
    self.state = np.ones((n_rows, n_cols), dtype=np.uint8)
    self.state[n_rows//2,n_cols//2] = 2

  def step(self):
    correlate2d(self.state,kernel,boundary='wrap',mode='same')

class Ant:
  def __init__(self, dir, clr):
    self.clr = clr #1/-1 True:White, False:Black
    self.dir = dir #1-4 1:N, 2:R, 3:S, 4:L

  def move(self):
    if self.clr == True:
      dir += 1
      if dir > 4:
        dir = 1
    else:
      dir -= 1
      if dir < 1:
        dir = 4
    return directions[dir]
    

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Create board
Step method
Ant class
